# PDF-specific configuration overrides
# Use with: quarto render --profile pdf

format:
  pdf:
    documentclass: scrbook
    classoption: 
      - paper=letter
      - fontsize=11pt
      - twoside
      - openright
      - chapterprefix=true
      - headings=standardclasses
    
    # Typography
    mainfont: "Source Sans Pro"
    sansfont: "Source Sans Pro"  
    monofont: "Source Code Pro"
    fontsize: 11pt
    linestretch: 1.15
    
    # Margins
    geometry:
      - left=1.25in
      - right=1.25in
      - top=1in
      - bottom=1in
      - bindingoffset=0.25in
    
    # Headers and footers
    pagestyle: headings
    
    # Code blocks
    highlight-style: github
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#2780e3"
    
    # Links
    colorlinks: true
    linkcolor: NavyBlue
    urlcolor: NavyBlue
    citecolor: NavyBlue
    
    # PDF metadata
    pdf-engine: xelatex
    keep-tex: false
    
    # Chapter formatting
    secnumdepth: 3
    
    # Include custom LaTeX
    include-in-header:
      - text: |
          \usepackage{fancyvrb}
          \usepackage{tcolorbox}
          \usepackage{etoolbox}
          \usepackage{booktabs}
          \usepackage{longtable}
          \usepackage{array}
          
          % Custom command for inline code
          \definecolor{inlinecodecolor}{RGB}{240,240,240}
          \let\oldtexttt\texttt
          \renewcommand{\texttt}[1]{\colorbox{inlinecodecolor}{\oldtexttt{#1}}}
          
          % Exercise boxes
          \newtcolorbox{exercisebox}[1][]{
            colback=blue!5!white,
            colframe=blue!75!black,
            title={#1},
            fonttitle=\bfseries
          }
          
          % Details/solution boxes  
          \newtcolorbox{detailsbox}[1][]{
            colback=gray!5!white,
            colframe=gray!75!black,
            title={#1},
            fonttitle=\bfseries,
            breakable
          }
          
          % Three Rules box
          \newtcolorbox{rulesbox}{
            colback=red!5!white,
            colframe=red!75!black,
            title={The Three Rules},
            fonttitle=\bfseries
          }
          
          % Custom chapter style
          \RedeclareSectionCommand[
            beforeskip=0pt,
            afterskip=1cm,
            font=\Huge\bfseries
          ]{chapter}
          
          % Page headers
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}
          \fancyhead[LE,RO]{\thepage}
          \fancyhead[LO]{\nouppercase{\rightmark}}
          \fancyhead[RE]{\nouppercase{\leftmark}}
          \renewcommand{\headrulewidth}{0.5pt}
          
          % Better tables
          \setlength{\tabcolsep}{8pt}
          \renewcommand{\arraystretch}{1.2}