# EPUB-specific configuration
# Use with: quarto render --profile epub

format:
  epub:
    # Metadata
    identifier:
      scheme: ISBN
      text: "978-0-000000-00-0"  # Replace with actual ISBN
    
    publisher: "Python Step by Step Publishing"
    rights: "© 2025 Norah Jones. All rights reserved."
    
    # Cover
    epub-cover-image: cover.png
    
    # Fonts
    epub-fonts:
      - assets/fonts/SourceSansPro-Regular.ttf
      - assets/fonts/SourceSansPro-Bold.ttf
      - assets/fonts/SourceSansPro-Italic.ttf
      - assets/fonts/SourceCodePro-Regular.ttf
    
    # Navigation
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    
    # Chapter numbering
    number-sections: true
    number-depth: 2
    
    # Code highlighting
    highlight-style: github
    
    # CSS customization
    css: assets/epub-styles.css
    
    # EPUB version
    epub-version: 3.0
    
    # Mathematics (if needed)
    html-math-method: mathml
    
    # Footnotes
    reference-location: chapter
    
    # Metadata for e-readers
    epub-metadata:
      - |
        <dc:subject>Computer Programming</dc:subject>
        <dc:subject>Python</dc:subject>
        <dc:subject>Educational Technology</dc:subject>
        <dc:subject>Artificial Intelligence</dc:subject>
        <meta property="dcterms:audience">Beginner Programmers</meta>
        <meta property="a11y:certifiedBy">Accessibility Verified</meta>
        <meta property="schema:accessMode">textual</meta>
        <meta property="schema:accessMode">visual</meta>
        <meta property="schema:accessModeSufficient">textual</meta>
        <meta property="schema:accessibilityFeature">alternativeText</meta>
        <meta property="schema:accessibilityFeature">readingOrder</meta>
        <meta property="schema:accessibilityFeature">structuralNavigation</meta>
        <meta property="schema:accessibilityFeature">tableOfContents</meta>
        <meta property="schema:accessibilityHazard">none</meta>